<!--h1>Administration</h1-->
<!--div class="navbar navbar-inverse navbar-fixed-top"-->
<div class="navbar navbar-inverse">
<!--div class="navbar"-->
    <div id="adminmenu" class="menu collapse navbar-collapse">
        <ul class="nav navbar-nav">
            <li<?php echo ($this->controllerName == 'category' ? ' class="active"' : ''); ?>>
                <a href="<?php echo $this->baseUrl('admin/category'); ?>">
                    Gestion des catégories
                </a>
            </li>
            <li<?php echo ($this->controllerName == 'provider' ? ' class="active"' : ''); ?>>
                <a href="<?php echo $this->baseUrl('admin/provider'); ?>">
                    Gestion des fournisseurs
                </a>
            </li>
            <li<?php echo ($this->controllerName == 'tax' ? ' class="active"' : ''); ?>>
                <a href="<?php echo $this->baseUrl('admin/tax'); ?>">
                    Gestion des taxes
                </a>
            </li>
            <li<?php echo ($this->controllerName == 'promotion' ? ' class="active"' : ''); ?>>
                <a href="<?php echo $this->baseUrl('admin/promotion'); ?>">
                    Gestion des promotions
                </a>
            </li>
            <li<?php echo ($this->controllerName == 'article' ? ' class="active"' : ''); ?>>
                <a href="<?php echo $this->baseUrl('admin/article'); ?>">
                    Gestion des articles
                </a>
            </li>
        </ul>
    </div>
</div>