<h1>Administration</h1>
<div id="adminmenu" class="menu">
    <ul>
        <li>
            <a href="<?php echo $this->baseUrl('admin/category');?>">
                Gestion des catégories
            </a>
        </li>
        <li>
            <a href="<?php echo $this->baseUrl('admin/provider');?>">
                Gestion des fournisseurs
            </a>
        </li>
        <li>
            <a href="<?php echo $this->baseUrl('admin/tax');?>">
                Gestion des taxes
            </a>
        </li>
        <li>
            <a href="<?php echo $this->baseUrl('admin/promotion');?>">
                Gestion des promotions
            </a>
        </li>
        <li>
            <a href="<?php echo $this->baseUrl('admin/article');?>">
                Gestion des articles
            </a>
        </li>
    </ul>
</div>