<div id="adminmenu" class="menu">
    <ul>
        <li>
            <a href="<?php echo $this->baseUrl('admin/');?>">
                Administration
            </a>
        </li>
        <li>
            <a href="<?php echo $this->baseUrl('stock/');?>">
                Stock
            </a>
        </li>
        <li>
            <a href="<?php echo $this->baseUrl('cash-register/');?>">
                Caisse
            </a>
        </li>
    </ul>
</div>