<div id="adminmenu" class="menu">
    <ul>
        <li>
            <a href="<?php echo $this->baseUrl('admin/');?>"<?php echo ($this->moduleName == 'admin' ? ' class="active"' : '');?>>
                Administration
            </a>
        </li>
        <li>
            <a href="<?php echo $this->baseUrl('stock/');?>"<?php echo ($this->moduleName == 'stock' ? ' class="active"' : '');?>>
                Stock
            </a>
        </li>
        <li>
            <a href="<?php echo $this->baseUrl('cash-register/');?>"<?php echo ($this->moduleName == 'cash-register' ? ' class="active"' : '');?>>
                Caisse
            </a>
        </li>
        <li>
            <a href="<?php echo $this->baseUrl('report/');?>"<?php echo ($this->moduleName == 'report' ? ' class="active"' : '');?>>
                Etats
            </a>
        </li>
        <li>
            <a href="<?php echo $this->baseUrl('purchase/');?>"<?php echo ($this->moduleName == 'purchase' ? ' class="active"' : '');?>>
                Gestion
            </a>
        </li>
    </ul>
</div>