<?php
$this->headLink()->appendStylesheet($this->baseUrl('/css/calendar.css'));
echo $this->action('create-form', 'income', 'purchase');
?>
<hr/>
<?php
echo $this->action('display-form', 'income', 'purchase');
?>
<script type="text/javascript" src="<?php echo $this->baseUrl('/js/calendar.js'); ?>"></script>
<script type="text/javascript">
    <!--
    init_evenement();
    -->
</script>
<?php
echo $this->action('display', 'income', 'purchase');
?>
<script type="text/javascript" src="<?php echo $this->baseUrl('/js/purchase/income.js'); ?>"></script>
<script type="text/javascript">
    <!--
    incomeInit();
    -->
</script>