<?php
$this->addHelperPath(APPLICATION_PATH . '/views/helpers', 'Application_View_Helper');
?>
<?php
echo $this->action('create-form', 'income', 'purchase');
?>
<hr/>
<?php
echo $this->action('display-form', 'income', 'purchase');
?>
<?php echo $this->trigCalendar(); ?>
<?php
echo $this->action('display', 'income', 'purchase');
?>
<script type="text/javascript" src="<?php echo $this->baseUrl('/js/purchase/income.js'); ?>"></script>
<script type="text/javascript">
    <!--
    incomeInit();
    //-->
</script>