<form method="post" action="<?php echo $this->baseUrl('admin/article/create'); ?>" id="createarticleform" class="createform adminform" role="form">
    <fieldset class="form-horizontal">
        <!--legend>Créer un article</legend-->
        <div class="form-group">
            <label for="ref" class="col-lg-3 control-label">Référence de l'article</label>
            <div class="col-lg-9">
                <input id="ref" name="ref" type="text" required autocomplete="off" placeholder="obligatoire" class="form-control"/>
            </div>
        </div>
        <div class="form-group">
            <label for="name" class="col-lg-3 control-label">Nom de l'article</label>
            <div class="col-lg-9">
                <input id="name" name="name" type="text" required autocomplete="off" placeholder="obligatoire" class="form-control"/>
            </div>
        </div>
        <div class="form-group">
            <label for="desc" class="col-lg-3 control-label">Description de l'article</label>
            <div class="col-lg-9">
                <textarea id="desc" name="desc" placeholder="facultatif" class="form-control"></textarea>
            </div>
        </div>
        <div class="form-group">
            <label for="priceht" class="col-lg-3 control-label">Prix TTC</label>
            <div class="col-lg-9">
                <input id="priceht" name="priceht" type="number" step=0.01 min=0 required autocomplete="off" placeholder="obligatoire" class="form-control"/>
            </div>
        </div>
        <div class="form-group">
            <label for="tva" class="col-lg-3 control-label">T.V.A</label>
            <div class="col-lg-9">
                <select id="tva" name="tva" required placeholder="obligatoire" class="form-control">
                    <option></option>
                    <?php echo $this->taxOptions($this->taxList); ?>
                </select>
            </div>
        </div>
        <div class="form-group">
            <label for="promo" class="col-lg-3 control-label">Promotions appliquées à l'article (optionnel)</label>
            <div class="col-lg-9">
                <select id="promo" name="promo" placeholder="optionnel" class="form-control">
                    <option></option>
                    <?php echo $this->promoOptions($this->promoList); ?>
                </select>
            </div>
        </div>
        <div class="form-group">
            <label for="cat" class="col-lg-3 control-label">Catégories auxquelles appartient l'article</label>
            <div class="col-lg-9">
                <select id="cat" name="cat[]" multiple="multiple" size="10" class="form-control">
                    <?php echo $this->categoryOptions($this->categoryTree); ?>
                </select>
            </div>
        </div>
        <div class="form-group">
            <label for="provider" class="col-lg-3 control-label">Fournisseur (optionnel)</label>
            <div class="col-lg-9">
                <select id="provider" name="provider" placeholder="optionnel" class="form-control">
                    <option></option>
                    <?php echo $this->providerOptions($this->providerList); ?>
                </select>
            </div>
        </div>
        <div class="form-group">
            <div class="col-lg-9 col-lg-offset-3">
                <div class="checkbox">
                    <label class="control-label">
                        Géré en stock <input id="stock" type="checkbox" name="stock"/>
                    </label>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label for="unit" class="col-lg-3 control-label">Unité de quantité</label>
            <div class="col-lg-9">
                <input id="unit" name="unit" type="text" autocomplete="off" placeholder="optionel" class="form-control"/>
            </div>
        </div>
        <div class="form-group">
            <div class="col-lg-9 col-lg-offset-3">
                <button type="submit" class="btn btn-primary">Créer</button>
            </div>
        </div>
    </fieldset>
</form>