<?php
$this->addHelperPath(dirname(__FILE__) . '/../../helpers', 'Admin_View_Helper');
$this->placeholder('nav')->set($this->action('menu', 'index', 'admin'));
?>
<div>
    <div class="panel panel-info">
        <div class="panel-heading">
            <button class="btn btn-default" data-toggle="collapse" data-target="#create-article">
                <span class="sr-only">Toggle Create Article</span>
                <i class="fa fa-bars"></i>
            </button>
            Créer un article
        </div>
        <div id="create-article" class="panel-body collapse">
            <?php echo $this->placeholder('forms')->create; ?>
        </div>
    </div>
    <div class="panel panel-info">
        <div class="panel-heading">
            <button class="btn btn-default" data-toggle="collapse" data-target="#update-article">
                <span class="sr-only">Toggle Update Article</span>
                <i class="fa fa-bars"></i>
            </button>
            Modifier un article
        </div>
        <div id="update-article" class="panel-body collapse">
            <?php echo $this->placeholder('forms')->update; ?>
        </div>
    </div>
</div>
<div id="articlelist">
    <table class="table table-condensed table-striped table-hover">
        <caption>Liste des articles</caption>
        <tr>
            <th>Référence</th>
            <th>Nom</th>
            <th>Description</th>
            <th>Catégories</th>
            <th>Prix HT</th>
            <th>TVA</th>
            <th>Promos</th>
            <th>Prix TTC</th>
            <th>Fournisseur</th>
        </tr>
        <?php
        echo $this->articleLines($this->articleList);
        ?>
    </table>
</div>
<?php $this->placeholder('scripts')->captureStart(); ?>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/admin/article.js'); ?>"></script>
<script type="text/javascript">
    <!--
    jQuery(document).ready(articleInit);
//-->
</script>
<?php
$this->placeholder('scripts')->captureEnd();
