<form method="post" action="<?php echo $this->baseUrl('admin/article/update'); ?>" id="updatearticleform" class="updateform adminform" role="form">
    <fieldset class="form-horizontal">
        <!--legend>Modifier un article</legend-->
        <div class="form-group">
            <label for="modref" class="col-lg-3 control-label">Référence de l'article à modifier</label>
            <div class="col-lg-9">
                <select id="modref" name="modref" required placeholder="obligatoire" class="form-control">
                    <option></option>
                    <?php echo $this->articleOptions($this->referenceList); ?>
                </select>
            </div>
        </div>
        <div class="form-group">
            <label for="modname" class="col-lg-3 control-label">Nom de l'article</label>
            <div class="col-lg-9">
                <input id="modname" name="modname" type="text" required autocomplete="off" placeholder="obligatoire" class="form-control"/>
            </div>
        </div>
        <div class="form-group">
            <label for="moddesc" class="col-lg-3 control-label">Description de l'article</label>
            <div class="col-lg-9">
                <textarea id="moddesc" name="moddesc" placeholder="facultatif" class="form-control"></textarea>
            </div>
        </div>
        <div class="form-group">
            <label for="modpriceht" class="col-lg-3 control-label">Prix TTC</label>
            <div class="col-lg-9">
                <input id="modpriceht" name="modpriceht" type="number" step=0.01 min=0 required autocomplete="off" placeholder="obligatoire" class="form-control"/>
            </div>
        </div>
        <div class="form-group">
            <label for="modtva" class="col-lg-3 control-label">T.V.A</label>
            <div class="col-lg-9">
                <select id="modtva" name="modtva" required placeholder="obligatoire" class="form-control">
                    <option></option>
                    <?php echo $this->taxOptions($this->taxList); ?>
                </select>
            </div>
        </div>
        <div class="form-group">
            <label for="modpromo" class="col-lg-3 control-label">Promotions appliquées à l'article (optionnel)</label>
            <div class="col-lg-9">
                <select id="modpromo" name="modpromo" placeholder="optionnel" class="form-control">
                    <option></option>
                    <?php echo $this->promoOptions($this->promoList); ?>
                </select>
            </div>
        </div>
        <div class="form-group">
            <label for="modcat" class="col-lg-3 control-label">Catégories auxquelles appartient l'article</label>
            <div class="col-lg-9">
                <select id="modcat" name="modcat[]" multiple="multiple" size="10" class="form-control">
                    <?php echo $this->categoryOptions($this->categoryTree); ?>
                </select>
            </div>
        </div>
        <div class="form-group">
            <label for="modprovider" class="col-lg-3 control-label">Fournisseur (optionnel)</label>
            <div class="col-lg-9">
                <select id="modprovider" name="modprovider" placeholder="optionnel" class="form-control">
                    <option></option>
                    <?php echo $this->providerOptions($this->providerList); ?>
                </select>
            </div>
        </div>
        <div class="form-group">
            <div class="col-lg-9 col-lg-offset-3">
                <div class="checkbox">
                    <label class="control-label">
                        Géré en stock <input id="modstock" name="modstock" type="checkbox"/>
                    </label>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label for="modunit" class="col-lg-3 control-label">Unité de quantité</label>
            <div class="col-lg-9">
                <input name="modunit" id="modunit" type="text" placeholder="optionel" autocomplete="off" class="form-control"/>
            </div>
        </div>
        <div class="form-group">
            <div class="col-lg-9 col-lg-offset-3">
                <button type="submit" class="btn btn-primary">Modifier</button>
            </div>
        </div>
    </fieldset>
</form>