<?php
$this->addHelperPath(realpath(dirname(__FILE__) . '/../../helpers'), 'Admin_View_Helper');
?>
<h1>Gestion des taxes</h1>
<div class="leftpart">
    <form method="post" action="<?php echo $this->baseUrl('admin/tax/create'); ?>" id="createtaxform" class="createform adminform">
        <fieldset>
            <legend>Créer une taxe</legend>
            <label for="name">Nom de la taxe</label>
            <input type="text" name="name" id="name" autocomplete="off"/>
            <br/>
            <label for="ratio">Ratio</label>
            <input type="number" step=0.01 name="ratio" id="ratio" autocomplete="off"/><span>%</span>
            <br/>
            <label for="desc">Description</label>
            <textarea id="desc" name="desc">(r.a.s.)</textarea>
            <br/>
            <input type="Submit" value="Créer"/>
        </fieldset>
    </form>
    <form method="post" action="<?php echo $this->baseUrl('admin/tax/update'); ?>" id="updatetaxform" class="updateform adminform">
        <fieldset>
            <legend>Modifier une taxe</legend>
            <?php
            echo $this->taxBox('modid', $this->taxes, 'Nom de la taxe à modifier');
            ?>
            <br/>
            <label for="modratio">Ratio</label>
            <input type="number" step=0.01 name="modratio" id="modratio" autocomplete="off"/><span>%</span>
            <br/>
            <label for="moddesc">Description</label>
            <textarea id="moddesc" name="moddesc">(r.a.s.)</textarea>
            <br/>
            <input type="Submit" value="Modifier"/>
        </fieldset>
    </form>
</div>
<div id="taxlist" class="listdisplay rightpart">
    <?php
    echo $this->taxList($this->taxes, 'Taxes existantes');
    ?>
</div>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/admin/tax.js'); ?>"></script>
<script type="text/javascript">
    jQuery(document).ready(taxInit);
</script>