<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="utf-8"/>
        <?php
        $this->headLink()->appendStylesheet($this->baseUrl('/css/style.css'));
        echo $this->headLink();
        $this->headScript(Zend_View_Helper_HeadScript::FILE, $this->baseUrl('/js/prototype.js'));
        echo $this->headScript();
        ?>
        <title>todo</title>
    </head>
    <body>
        <?php
        echo $this->action('main-menu', 'index', 'default');
        ?>
        <h1>Gestion du stock</h1>
        <?php
        echo $this->layout()->content;
        ?>
    </body>
</html>
