<?php if ($this->pageCount): ?>
    <div class="paginationControl">
        <!-- Previous page link -->
        <?php if (isset($this->previous)): ?>
            <a href="<?php echo $this->url(array('page' => 1)); ?>" class="btn btn-primary"><i class="fa fa-fast-backward"></i></a>
            <a href="<?php echo $this->url(array('page' => $this->previous)); ?>" class="btn btn-primary"><i class="fa fa-step-backward"></i></a>
        <?php else: ?>
            <a href="#" class="btn btn-default disabled"><i class="fa fa-fast-backward"></i></a>
            <a href="#" class="btn btn-default disabled"><i class="fa fa-step-backward"></i></a>
        <?php endif; ?>
        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current) : ?>
                <a href="<?php echo $this->url(array('page' => $page)); ?>" class="btn btn-default"><?php echo $page; ?></a>
            <?php else: ?>
                <a href="#" class="btn btn-info disabled"><?php echo $page; ?></a>
            <?php endif; ?>
        <?php endforeach; ?>
        <!-- Next page link -->
        <?php if (isset($this->next)): ?>
            <a href="<?php echo $this->url(array('page' => $this->next)); ?>" class="btn btn-primary"><i class="fa fa-step-forward"></i></a>
            <a href="<?php echo $this->url(array('page' => $this->pageCount)); ?>" class="btn btn-primary"><i class="fa fa-fast-forward"></i></a>
        <?php else: ?>
            <a href="#" class="btn btn-default disabled"><i class="fa fa-step-forward"></i></a>
            <a href="#" class="btn btn-default disabled"><i class="fa fa-fast-forward"></i></a>
        <?php endif; ?>
    </div>
<?php endif; ?>

<?php if (false && $this->count): ?>
    <div class="paginationControl">
        <!-- Previous page link -->
        <?php if (NULL !== $this->previous): ?>
            <a href="//<?php echo $this->url(array('page' => $this->previous)); ?>" class="btn btn-primary"><i class="fa fa-chevron-left"></i></a>
        <?php else: ?>
            <a href="#" class="btn btn-default disabled"><i class="fa fa-chevron-left"></i></a>
        <?php endif; ?>
        <!-- Numbered page links -->
        <?php foreach ($this->range as $page): ?>
            <?php if ($page != $this->page) : ?>
                <a href="//<?php echo $this->url(array('page' => $page)); ?>" class="btn btn-default"><?php echo $page; ?></a>
            <?php else: ?>
                <a href="#" class="btn btn-info disabled">//<?php echo $page; ?></a>
            <?php endif; ?>
        <?php endforeach; ?>
        <!-- Next page link -->
        <?php if (NULL !== $this->next): ?>
            <a href="//<?php echo $this->url(array('page' => $this->next)); ?>" class="btn btn-primary"><i class="fa fa-chevron-right"></i></a>
        <?php else: ?>
            <a href="#" class="btn btn-default disabled"><i class="fa fa-chevron-right"></i></a>
            <?php endif; ?>
    </div>
<?php endif; ?>