<?php $this->headLink()->appendStylesheet($this->baseUrl('/css/calendar.css')); ?>
<form method="post" action="<?php echo $this->baseUrl('purchase/create'); ?>">
    <fieldset>
        <legend>Création</legend>
        <label for="purchasedate">Date</label>
        <input class="calendrier" type="date" name="purchasedate" autocomplete="off"/>
        <label for="purchaseitem">Description</label>
        <textarea name="purchaseitem"></textarea>
        <label for="purchasettc">Montant TTC</label>
        <input type="number" name="purchasettc" autocomplete="off"/>
        <label for="purchaseht">Montant HT</label>
        <input type="number" name="purchaseht" autocomplete="off"/>
        <label for="purchasetax">TVA</label>
        <select name="purchasetax">
            <option value="19.6" selected="selected">19,60 %</option>
            <option value="7">7 %</option>
        </select>
        <label for="purchasemode">Mode de paiement</label>
        <select name="purchasemode">
            <option value="">- -</option>
            <option value="cb">CB</option>
            <option value="chq">Chèque</option>
            <option value="mon">Espèces</option>
        </select>
        <input type="submit" value="OK"/>
    </fieldset>
</form>
<form method="post" action="<?php echo $this->baseUrl('purchase/display'); ?>">
    <fieldset>
        <legend>Période affichée</legend>
        <noscript>
        <fieldset>
            <legend>Début</legend>
            <label for="year">Année</label>
            <input type="number" name="startyear" value="<?php echo $this->startyear; ?>" autocomplete="off"/>
            <label for="month">Mois</label>
            <input type="number" name="startmonth" value="<?php echo $this->startmonth; ?>" autocomplete="off"/>
            <label for="day">Jour</label>
            <input type="number" name="startday" value="<?php echo $this->startday; ?>" autocomplete="off"/>
        </fieldset>
        <fieldset>
            <legend>Fin</legend>
            <label for="year">Année</label>
            <input type="number" name="endyear" value="<?php echo $this->endyear; ?>" autocomplete="off"/>
            <label for="month">Mois</label>
            <input type="number" name="endmonth" value="<?php echo $this->endmonth; ?>" autocomplete="off"/>
            <label for="day">Jour</label>
            <input type="number" name="endday" value="<?php echo $this->endday; ?>" autocomplete="off"/>
        </fieldset>
        <input type="submit" value="OK" />
        </noscript>
        <fieldset id="calendarscripted" disabled="disabled" style="display: none;">
            <label for="year">Début</label>
            <input class="calendrier" type="date" name="startfulldate" value="<?php echo $this->startfulldate; ?>" autocomplete="off"/>
            <label for="year">Fin</label>
            <input class="calendrier" type="date" name="endfulldate" value="<?php echo $this->endfulldate; ?>" autocomplete="off"/>
            <input type="submit" value="OK" />
        </fieldset>
    </fieldset>
</form>
<script type="text/javascript">
    <!--
    var calendarFieldSet = $('calendarscripted');
    calendarFieldSet.removeAttribute('disabled');
    calendarFieldSet.removeAttribute('style');
    -->
</script>
<script type="text/javascript" src="<?php echo $this->baseUrl('/js/calendar.js'); ?>"></script>
<script type="text/javascript">
    <!--
    init_evenement();
    -->
</script>
<?php
echo $this->action('display', 'index', 'purchase');
?>