<?php
$this->addHelperPath(APPLICATION_PATH . '/views/helpers', 'Application_View_Helper');
$this->headLink()->offsetSetStylesheet(10, $this->baseUrl('/css/purchase.css'));
$this->placeholder('nav')->set($this->action('menu', 'index', 'purchase'));
?>
<div class="col-md-12">
    <?php
    echo $this->action('create-form', 'manage', 'purchase');
    echo $this->action('display-form', 'index', 'purchase');
    echo $this->action('display', 'index', 'purchase');
    ?>
</div>
<?php $this->placeholder('scripts')->captureStart(); ?>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/purchase/purchase.js'); ?>"></script>
<script>
    <!--
    purchaseInit();
    //-->
</script>
<?php
echo $this->trigCalendar();
$this->placeholder('scripts')->captureEnd();