<?php
$this->addHelperPath(APPLICATION_PATH . '/views/helpers', 'Application_View_Helper');
?>
<?php
echo $this->action('create-form', 'manage', 'purchase');
?>
<hr/>
<?php
echo $this->action('display-form', 'index', 'purchase');
?>
<script type="text/javascript" src="<?php echo $this->baseUrl('/js/calendar.js'); ?>"></script>
<script type="text/javascript">
    <!--
    init_evenement();
    //-->
</script>
<?php
echo $this->action('display', 'index', 'purchase');
?>
<?php echo $this->trigCalendar(); ?>