<h1>Achats</h1>
<div id="purchasemenu" class="menu">
    <ul>
        <li>
            <a href="<?php echo $this->baseUrl('purchase/index/manage');?>">
                Achats
            </a>
        </li>
        <li>
            <a href="<?php echo $this->baseUrl('purchase/cash/index');?>">
                Fond de caisse
            </a>
        </li>
        <li>
            <a href="<?php echo $this->baseUrl('purchase/income/index');?>">
                Entrées
            </a>
        </li>
    </ul>
</div>