<!--div id="purchasemenu" class="menu navbar navbar-inverse"-->
    <ul class="nav navbar-nav navbar-right">
        <li<?php echo ($this->controllerName == 'index' ? ' class="active"' : '');?>>
            <a href="<?php echo $this->baseUrl('purchase/index/manage');?>">
                Achats
            </a>
        </li>
        <!--li<?php echo ($this->controllerName == 'cash' ? ' class="active"' : '');?>>
            <a href="<?php echo $this->baseUrl('purchase/cash/index');?>">
                Fond de caisse
            </a>
        </li>
        <li<?php echo ($this->controllerName == 'income' ? ' class="active"' : '');?>>
            <a href="<?php echo $this->baseUrl('purchase/income/index');?>">
                Entrées
            </a>
        </li-->
    </ul>
<!--/div-->