<h1>Gestion</h1>
<div id="purchasemenu" class="menu">
    <ul>
        <li>
            <a href="<?php echo $this->baseUrl('purchase/index/manage');?>"<?php echo ($this->controllerName == 'index' ? ' class="active"' : '');?>>
                Achats
            </a>
        </li>
        <!--li>
            <a href="<?php echo $this->baseUrl('purchase/cash/index');?>"<?php echo ($this->controllerName == 'cash' ? ' class="active"' : '');?>>
                Fond de caisse
            </a>
        </li>
        <li>
            <a href="<?php echo $this->baseUrl('purchase/income/index');?>"<?php echo ($this->controllerName == 'income' ? ' class="active"' : '');?>>
                Entrées
            </a>
        </li-->
    </ul>
</div>