<?php
$this->headLink()->appendStylesheet($this->baseUrl('/css/calendar.css'));
echo $this->action('update-form', 'manage', 'purchase');
?>
<script type="text/javascript">
    <!--
    var calendarFieldSets = $$('*[class~="calendarscripted"]');
    calendarFieldSets.each(function (item) {
        item.removeAttribute('disabled');
        item.removeAttribute('style');
    });
    -->
</script>
<script type="text/javascript" src="<?php echo $this->baseUrl('/js/calendar.js'); ?>"></script>
<script type="text/javascript">
    <!--
    init_evenement();
    -->
</script>
