<h3>Ticket : <?php echo $this->hash; ?></h3>
<pre><?php echo $this->soldArticles($this->soldArticles); ?>

TOTAL <?php echo $this->currency($this->totalSalePrice); ?>

    <?php echo $this->taxBreakDown($this->totalTax, $this->totalRawPrice); ?>
</pre>
<form id="paymentForm" method="post" action="<?php echo $this->baseUrl('cash-register/front-end/register'); ?>">
    <input id="total" type="hidden" name="total" value="<?php echo $this->totalSalePrice; ?>"/>
    <input id="hash" type="hidden" name="hash" value="<?php echo $this->hash; ?>"/>
    <fieldset>
        <?php echo $this->paymentList($this->paymentList, 'payment'); ?>
        <br />
        <br />
        <fieldset class="moneyfields invisible">
            <label for="given">Perçu</label><br />
            <input id="given" type="text" name="given" value="0"/>
            <br />
            <label for="returned">A rendre</label><br />
            <input id="returned" type="text" name="returned" readonly="readonly" value="0"/>
        </fieldset>
        <fieldset class="chrfields invisible">
            <label for="chrgiven">Perçu</label><br />
            <input id="chrgiven" type="text" name="chrgiven" value="0"/>
        </fieldset>
        <br />
        <input type="submit" value="OK"/>
    </fieldset>
</form>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/cash-register/pay.js'); ?>"></script>
<script type="text/javascript">
    payInit();
</script>