<?php
$this->addHelperPath(dirname(__FILE__) . '/../../helpers', 'Purchase_View_Helper');
?>
<?php
$this->addHelperPath(APPLICATION_PATH . '/views/helpers', 'Application_View_Helper');
?>
<?php
echo $this->action('insert-form', 'cash', 'purchase');
?>
<hr/>
<?php
echo $this->action('display-form', 'cash', 'purchase');
?>
<?php echo $this->trigCalendar(); ?>
<?php
echo $this->action('display', 'cash', 'purchase');
?>