<form class="purchaseform form-inline" method="post" action="<?php echo $this->baseUrl('purchase/manage/create'); ?>">
    <fieldset>
        <legend>Création</legend>
        <div class="form-group">
            <label for="purchasedate" class="control-label">Date</label>
            <br />
            <input class="calendrier form-control" type="date" name="purchasedate" autocomplete="off"/>
        </div>
        <div class="form-group">
            <br/>
            <label for="purchaseitem" class="control-label">Description</label>
            <br />
            <textarea name="purchaseitem" class="form-control"></textarea>
        </div>
        <div class="form-group">
            <label for="purchasettc" class="control-label">Montant TTC</label>
            <br />
            <input type="number" step=0.01 name="purchasettc" autocomplete="off" class="form-control"/>
        </div>
        <div class="form-group">
            <label for="purchaseht" class="control-label">Montant HT</label>
            <br />
            <input type="number" step=0.01 name="purchaseht" autocomplete="off" class="form-control"/>
        </div>
        <div class="form-group">
            <label for="purchasetax" class="control-label">TVA</label>
            <br />
            <select name="purchasetax" class="form-control">
                <option value="19.6" selected="selected">19,60 %</option>
                <option value="7">7 %</option>
                <option value="5.5">5,5 %</option>
                <option value="0">0 %</option>
            </select>
        </div>
        <div class="form-group">
            <label for="purchasemode" class="control-label">Mode de paiement</label>
            <br />
            <select name="purchasemode" class="form-control">
                <option value="">- -</option>
                <option value="cb">CB</option>
                <option value="chq">Chèque</option>
                <option value="mon">Espèces</option>
            </select>
        </div>
        <div class="checkbox">
            <br />
            <label class="control-label">
                <input type="checkbox" name="offmargin"> Hors-marge
            </label>
        </div>
        <div class="form-group">
            <br/>
            <input type="submit" value="Valider" class="btn btn-primary"/>
        </div>
    </fieldset>
</form>