<?php
$this->addHelperPath(realpath(dirname(__FILE__) . '/../../helpers'), 'CashRegister_View_Helper');
$this->headLink()->offsetSetStylesheet(10, $this->baseUrl('/css/cash-register.css'));
?>
<div id="choice" class="col-lg-8">
    <div class="row">
        <div class="col-lg-8">
            <div id="search" class="dropdown">
                <input id="drop1" class="dropdown-toggle form-control" data-toggle="dropdown"/>
                <ul class="dropdown-menu" role="menu" aria-labelledby="drop1"></ul>
            </div>
        </div>
        <div id="search-article" class="col-lg-4">

        </div>
    </div>
    <hr/>
    <div id="categorypad" class="touchpad">
        <?php echo $this->categoryPad($this->categoryTree); ?>
    </div>
    <div id="subcategorypad" class="touchpad"></div>
    <div id="articlepad" class="touchpad"></div>
</div>
<div id="billing" class="col-lg-4">
    <div id="modificators">
        <div id="quantity" style="display: none;">
            <input type="button" qty="2" value="x2"/><input type="button" qty="3" value="x3"/><input type="button" qty="4" value="x4"/><input type="button" qty="5" value="x5"/>
        </div>
        <div id="promo">
            <button id="promoToggle" type="button" class="button btn btn-default">Promotions</button><button id="promoRemove" type="button" class="button btn btn-default">Sans promotion</button>
            <div id="promoPad">
                <?php echo $this->promoPad($this->promoList); ?>
            </div>
        </div>
    </div>
    <form id="bill" method="post" action="<?php echo $this->baseUrl('cash-register/index/pay'); ?>">
        <fieldset>
            <input type="submit" value="Enregistrer" class="button btn btn-warning"/><input id="total" type="text" disabled="disabled" class="input-lg" value="<?php $this->currency(0); ?>"/>
        </fieldset>
        <fieldset>
            <div id="billList"></div>
        </fieldset>
    </form>
</div>
<?php $this->placeholder('scripts')->captureStart(); ?>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/cash-register/front-end.js'); ?>"></script>
<script type="text/javascript">
    <!--
    jQuery(document).ready(function() {
        frontEndInit('<?php echo $this->baseUrl('images/ajax-loading.gif'); ?>', <?php echo ArticleMapper::MINIMUM_SEARCH_SIZE; ?>);
    });
//-->
</script>
<?php
$this->placeholder('scripts')->captureEnd();
