<?php
$this->addHelperPath(realpath(dirname(__FILE__) . '/../../helpers'), 'Admin_View_Helper');
$this->placeholder('nav')->set($this->action('menu', 'index', 'admin'));
?>
<div>
    <div class="col-lg-4">
        <form method="post" action="<?php echo $this->baseUrl('admin/category/create'); ?>" id="createcategoryform">
            <fieldset>
                <legend>Créer une catégorie</legend>
                <div class="form-group">
                    <label for="categoryref">Référence de la catégorie</label>
                    <input id="categoryref" type="text" name="categoryref" autocomplete="off" class="form-control" required/>
                </div>
                <div class="form-group">
                    <label for="categoryname">Nom de la catégorie</label>
                    <input id="categoryname" type="text" name="categoryname" autocomplete="off" class="form-control" required/>
                </div>
                <div class="form-group">
                    <label for="categorydesc">Description de la catégorie</label>
                    <textarea id="categorydesc" name="categorydesc" placeholder="facultatif" class="form-control"></textarea>
                </div>
                <div class="form-group">
                    <?php
                    echo $this->categoryBox(
                            'parentcategory', $this->categoryTree, 'Catégorie parente (optionel)', true
                    );
                    ?>
                </div>
                <button type="submit" class="btn btn-primary">Créer</button>
            </fieldset>
        </form>
        <form method="post" action="<?php echo $this->baseUrl('admin/category/update'); ?>" id="updatecategoryform">
            <fieldset>
                <legend>Modifier une catégorie</legend>
                <div class="form-group">
                    <?php
                    echo $this->categoryBox(
                            'modcategoryref', $this->categoryTree, 'Catégorie à modifier', false, NULL, true
                    );
                    ?>
                </div>
                <div class="form-group">
                    <label for="modcategoryname">Nom de la catégorie</label>
                    <input id="modcategoryname" type="text" name="modcategoryname" autocomplete="off" class="form-control" required/>
                </div>
                <div class="form-group">
                    <label for="modcategorydesc">Description de la catégorie</label>
                    <textarea id="modcategorydesc" name="modcategorydesc" placeholder="facultatif" class="form-control"></textarea>
                </div>
                <div class="form-group">
                    <?php
                    echo $this->categoryBox(
                            'modparentcategory', $this->categoryTree, 'Catégorie parente (optionel)', true
                    );
                    ?>
                </div>
                <button type="submit" class="btn btn-primary">Modifier</button>
            </fieldset>
        </form>
    </div>
    <div id="categorylist" class="col-lg-8">
        <?php
        echo $this->categoryList($this->categoryTree);
        ?>
    </div>
</div>
<?php $this->placeholder('scripts')->captureStart(); ?>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/admin/category.js'); ?>"></script>
<script type="text/javascript">
    jQuery(document).ready(categoryInit);
</script>
<?php $this->placeholder('scripts')->captureEnd(); ?>