<?php
$this->addHelperPath(APPLICATION_PATH . '/views/helpers', 'Application_View_Helper');
?>
<h1>Détail des opérations</h1>
<form method="post" action="<?php echo $this->baseUrl('report/index/detail'); ?>">
    <fieldset>
        <legend>Période affichée</legend>
        <fieldset>
            <label for="year">Début</label>
            <input class="calendrier" type="date" name="startfulldate" value="<?php echo $this->startfulldate; ?>" autocomplete="off"/>
            <label for="year">Fin</label>
            <input class="calendrier" type="date" name="endfulldate" value="<?php echo $this->endfulldate; ?>" autocomplete="off"/>
            <input type="submit" value="OK" />
        </fieldset>
    </fieldset>
</form>
<a href="<?php echo $this->baseUrl('report/index/csv/startfulldate/' . $this->startfulldate . '/endfulldate/' . $this->endfulldate) ?>">Télécharger</a>
<table>
    <?php
    $lines = explode(PHP_EOL, $this->content);
    $line1 = array_shift($lines);

    echo '<tr>';

    $cells = explode(';', $line1);
    foreach ($cells as $cell)
    {
        echo '<th>' . $cell . '</th>';
    }

    echo '</tr>';

    foreach ($lines as $csvLine)
    {
        if (!empty($csvLine))
        {
            echo '<tr>';

            $cells = explode(';', $csvLine);
            foreach ($cells as $cell)
            {
                echo '<td>' . $cell . '</td>';
            }

            echo '</tr>';
        }
    }
    ?>
</table>
<?php echo $this->trigCalendar(); ?>