<?php
$this->addHelperPath(APPLICATION_PATH . '/views/helpers', 'Application_View_Helper');
$this->placeholder('nav')->set($this->action('menu', 'index', 'report'));
?>
<div class="col-lg-4">
    <form method="post" class="form-inline" action="<?php echo $this->baseUrl('report/index/margin'); ?>">
        <fieldset>
            <label for="date">Date de référence</label>
            <div class="form-group">
                <input class="calendrier form-control" type="date" name="date" value="<?php echo $this->date; ?>" autocomplete="off"/>
            </div>
            <input type="submit" value="Valider" class="btn btn-primary"/>
        </fieldset>
    </form>
    <?php if ($this->margin !== null) : ?>
        <hr/>
        <table class="table">
            <tr><th>Taux de marge</th></tr>
            <tr><td class="numeric-cell"><?php echo $this->margin; ?> %</td></tr>
        </table>
    <?php endif; ?>
</div>
<?php
echo $this->trigCalendar();
