<?php

header('Content-Type: application/csv', true);
header('Content-Disposition: attachment; filename="CafePoisPlumes_CA_' . $this->year . '-' . $this->month . '.csv"', true);

if (empty($this->report))
{
    return;
}

echo 'DECLARATION DE CHIFFRE D\'AFFAIRE ' . $this->year . ' ' . $this->month . PHP_EOL . PHP_EOL;

echo 'Extraction datée du ' . $this->date->getIso() . PHP_EOL . PHP_EOL;

echo implode(';', array('ANNEE', 'MOIS', 'Taux', 'TTC', 'HT')) . PHP_EOL;
foreach ($this->report as $line)
{
    echo implode(';', array(
        $line->year,
        $line->month,
        $line->tva . ' %',
        $this->currency($line->ttc),
        $this->currency($line->ht)
    ))
    . PHP_EOL;
}
