<?php
$this->addHelperPath(dirname(__FILE__) . '/../../helpers', 'Admin_View_Helper');
?>
<!--h1>Gestion des fournisseurs</h1-->
<div class="leftpart col-md-4">
    <form method="post" action="<?php echo $this->baseUrl('admin/provider/create'); ?>" id="createproviderform" class="createform adminform">
        <fieldset>
            <legend>Créer un founisseur</legend>
            <div class="form-group">
                <label for="name">Nom</label>
                <input type="text" name="name" id="name" autocomplete="off" class="form-control"/>
            </div>
            <div class="form-group">
                <label for="info">Informations et coordonnées</label>
                <textarea name="info" id="info" placeholder="Adresse, téléphone,..." class="form-control"></textarea>
            </div>
            <div class="form-group">
                <label for="comment">Commentaires</label>
                <textarea name="comment" id="comment" placeholder="Notes libres" class="form-control"></textarea>
            </div>
            <input type="submit" class="btn btn-primary" value="Créer"/>
        </fieldset>
    </form>
    <form method="post" action="<?php echo $this->baseUrl('admin/provider/update'); ?>" id="updateproviderform" class="updateform adminform">
        <fieldset>
            <legend>Modifier un fournisseur</legend>
            <div class="form-group">
                <?php
                echo $this->providerBox(
                        'modid', $this->providerList, 'Nom du fournisseur à modifier'
                );
                ?>
            </div>
            <div class="form-group">
                <label for="modinfo">Informations et coordonnées</label>
                <textarea name="modinfo" id="modinfo" placeholder="Adresse, téléphone,..." class="form-control"></textarea>
            </div>
            <div class="form-group">
                <label for="modcomment">Commentaires</label>
                <textarea name="modcomment" id="modcomment" placeholder="Notes libres" class="form-control"></textarea>
            </div>
            <input type="submit" class="btn btn-primary" value="Modifier"/>
        </fieldset>
    </form>
</div>
<div id="providerlist" class="rightpart col-md-8">
    <?php
    echo $this->providerList($this->providerList, 'Fournisseurs existants');
    ?>
</div>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/admin/provider.js'); ?>"></script>
<script type="text/javascript">
    providerInit();
</script>